[package]
name = "micro-http-server"
version = "0.1.8"
authors = ["tokiedokie <42903136+tokiedokie@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = true
panic = 'abort'

[[bin]]
bench = false
path = "src/main.rs"
name = "mhs"

[dependencies]
